namespace: dev

frontend:
  image: davidgalstyan/frontend-app:latest
  replicas: 2
  containerPort: 80
  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 31000


backend:
  image: davidgalstyan/backend-app:latest
  replicas: 2
  containerPort: 7000

  config:
    DB_HOST: db
    DB_PORT: "5432"
    DB_USERNAME: postgres
    DB_DATABASE: devops_lessons
    PORT: "7000"
    HOST: localhost
    APP_NAME: Lessons
    APP_DESCRIPTION: Devops lessons REST API
    NODE_ENV: development

  service:
    type: ClusterIP
    port: 7000
    targetPort: 7000


postgres:
  image: postgres
  replicas: 2
  containerPort: 5432

  config:
    POSTGRES_USER: postgres
    POSTGRES_DB: devops_lessons

  service:
    name: db
    port: 5432
    targetPort: 5432
    type: ClusterIP

  volume:
    path: /data/postgres
