apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_USER: {{ .Values.postgres.config.POSTGRES_USER | quote }}
  POSTGRES_DB: {{ .Values.postgres.config.POSTGRES_DB | quote }}
