apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: {{ .Values.postgres.service.port }}
    targetPort: {{ .Values.postgres.service.targetPort }}
  type: {{ .Values.postgres.service.type }}
