apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: {{ .Values.backend.config.DB_HOST | quote }}
  DB_PORT: {{ .Values.backend.config.DB_PORT | quote }}
  DB_USERNAME: {{ .Values.backend.config.DB_USERNAME | quote }}
  DB_DATABASE: {{ .Values.backend.config.DB_DATABASE | quote }}
  PORT: {{ .Values.backend.config.PORT | quote }}
  HOST: {{ .Values.backend.config.HOST | quote }}
  APP_NAME: {{ .Values.backend.config.APP_NAME | quote }}
  APP_DESCRIPTION: {{ .Values.backend.config.APP_DESCRIPTION | quote }}
  NODE_ENV: {{ .Values.backend.config.NODE_ENV | quote }}
